version: "3"
services:
  service:
    build:
      context: .
      dockerfile: dev.Dockerfile  
    # ports:
    #   - "8080:8080"
    working_dir: /app
    volumes:
      - .:/app #:delegated -> enable for better performance, but less write guarantees
      - ./.pkg:/go/pkg #:delegated -> enable for better performance, but less write guarantees      
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres

  postgres:
    image: postgres:12.2-alpine
    container_name: go-mranftl-sample_postgres
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=9bed16f749d74a3c8bfbced18a7647f5
      - POSTGRES_DB=sample
    volumes:
      - .:/app
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume: #declare a named volume to persist DB data