[psql]
    # Connection params are injected via env vars (PSQL_*)
    # see https://github.com/volatiletech/sqlboiler/issues/678
    # see https://github.com/volatiletech/sqlboiler/pull/615
    # dbname = PSQL_DBNAME
    # user = PSQL_USER
    # pass = PSQL_PASS
    # host = PSQL_HOST
    # port = PSQL_PORT
    # sslmode = PSQL_SSLMODE
    # schema = PSQL_SCHEMA
  dbname = "sample"
  host   = "192.168.124.13"
  port   = 5432
  user   = "dbuser"
  pass   = "9bed16f749d74a3c8bfbced18a7647f5"
  sslmode = "disable"
  schema = "public"
     
    blacklist = ["migrations"]